@PORT = 3000

### Create a User
POST http://localhost:{{PORT}}/users
Content-Type: application/json

{
  "password": "password_2222",
  "email": "user_2222@example.com"
}

### Post Login
POST http://localhost:{{PORT}}/auth/login
Content-Type: application/json

{
  "username": "user_2222",
  "password": "password_2222"
}


### Get Reservations
GET http://localhost:{{PORT}}/reservations

### Create a Reservation
POST http://localhost:{{PORT}}/reservations
Content-Type: application/json

{
	"startDate": "2026-02-01",
	"endDate": "2026-02-05",
	"userId": "user_2222",
	"placeId": "place_2222",
	"invoiceId": "invoice_2222"
}

> {%
  client.global.set("reservationId", response.body._id);
%}

### GET Reservations by ID

GET http://localhost:{{PORT}}/reservations/{{reservationId}}
