@PORT = 3000

### Get Reservations
GET http://localhost:{{PORT}}/reservations

### Create a Reservation
@Access_Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YThmNGI3NWE4YzNkYTJmZDJjMWI3YzciLCJpYXQiOjE3ODgwMjIyOTEsImV4cCI6MTc4ODAyNTg5MX0.8bjHBZ4RAYXyLJ5dzzaCfqCTF9WWDzVmrgVcqIr_SyE
POST http://localhost:{{PORT}}/reservations
Content-Type: application/json

{
	"startDate": "2026-02-01",
	"endDate": "2026-02-05",
	"userId": "user_2222",
	"placeId": "place_2222",
	"invoiceId": "invoice_2222"
}

> {%
  client.global.set("reservationId", response.body._id);
%}

### GET Reservations by ID

GET http://localhost:{{PORT}}/reservations/{{reservationId}}
