@PORT = 3000

### Get Reservations
GET http://localhost:{{PORT}}/reservations

### Create a Reservation
@Access_Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YThmNGI3NWE4YzNkYTJmZDJjMWI3YzciLCJpYXQiOjE3ODc4NjQ2NTksImV4cCI6MTc4Nzg2ODI1OX0.60FssQx-8b-ySl3ECvjHN36jqB_yTorw2vBCo_J_O14
POST http://localhost:{{PORT}}/reservations
Authorization: Bearer {{Access_Token}}
Content-Type: application/json

{
	"startDate": "2026-02-01",
	"endDate": "2026-02-05",
	"userId": "user_2222",
	"placeId": "place_2222",
	"invoiceId": "invoice_2222"
}

> {%
  client.global.set("reservationId", response.body._id);
%}

### GET Reservations by ID

GET http://localhost:{{PORT}}/reservations/{{reservationId}}
