services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/DockerFile
      target: development
    command: node dist/apps/reservations/main
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/sleepr-mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
