services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/DockerFile
      target: development
    command: pnpm run start:dev reservations
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    environment:
      - RESERVATIONS_PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/sleepr-mongo

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/DockerFile
      target: development
    command: pnpm run start:dev auth
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    environment:
      - AUTH_PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/sleepr-mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
